bar:
  height: 28
  location: top
  background: 1a1b26ff
  foreground: d2d9f8ff
  font: JetBrainsMono NF:weight=bold:pixelsize=16
  spacing: 15

  left:
    - dwl:
        number-of-tags: 9
        dwl-info-filename: "/home/nikita/.cache/dwlinfo"
        content:
          list:
            items:
              - map:
                  conditions:
                    selected:
                      string: {text: "{id}", margin: 12, deco: {background: {color: 5e5f67ff}}}
                    ~empty:
                      string: {text: "{id}", margin: 12, foreground: d2d9f8ff}
                    empty && id != 0:
                      string: {text: "{id}", margin: 12, foreground: 5e5f67ff}
                    urgent: {string: {text: "=> {id} <="}}
                    id == 0: {string: {text: "{layout} {title}", max: 100}}

  right:
    - backlight:
        name: intel_backlight
        content:
          - string: {text: "󰖨", font: "JetBrainsMono NF:weight=bold:pixelsize=22", right-margin: 10}
          - string: {text: "{percent}%"}
    - pulse:
        content:
          map:
            conditions:
              ~sink_muted:
                - ramp:
                    tag: sink_percent
                    font: "JetBrainsMono Nerd Font:weight=bold:pixelsize=25"
                    right-margin: 5
                    items:
                      - string: {text: "󰕿"}
                      - string: {text: "󰖀"}
                      - string: {text: "󰕾"}
                - string: {text: "{sink_percent}%"}
              sink_muted:
                - string: {text: "󰖁", font: "JetBrainsMono Nerd Font:weight=bold:pixelsize=25", right-margin: 7}
                - string: {text: "muted"}
    - battery:
        name: BAT0
        content:
          - ramp:
              tag: capacity
              font: "JetBrainsMono Nerd Font:weight=bold:pixelsize=22"
              right-margin: 15
              items:
                - string: {text: ""}
                - string: {text: ""}
                - string: {text: ""}
                - string: {text: ""}
                - string: {text: ""}
          - string: {text: "{capacity}%"}
    - mem:
        poll-interval: 2000
        content:
          - string: {text: "", font: "JetBrainsMono Nerd Font:weight=bold:pixelsize=20", right-margin: 10}
          - string: {text: "{used:mb}Mi"}
    - network:
        poll-interval: 5000
        content:
          map:
            default:
              empty: {}
            conditions:
              name == "wlo1":
                - string: {text: "󰤨", font: "JetBrainsMono Nerd Font:weight=bold:pixelsize=21", right-margin: 12}
                - string: {text: "{ssid}"}

    - clock:
        content:
          - string: {text: "󰥔", font: "JetBrainsMono Nerd Font:weight=bold:pixelsize=21", right-margin: 10}
          - string: {text: "{time}", right-margin: 10}
